--hud = {
--  ranking = 0
--  }
--function hud.load()
--end
--function hud.update(dt)
--  ranking = ranking + 100
--  end
--function hud.draw()
--  love.graphics.newFont("Reboard.otf", 20)
--  love.graphics.print("" .. hud.ranking .. "", 50, 150)
--end